version: '2'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'
      LANG: ja_JP.UTF-8
    volumes:
      - /.data/boardless/:/var/lib/postgresql/data:Z
    networks:
      - my-network
  deploys-db:
    build: .
    image: tampopos/deploys-db:latest
    environment:
      - ConnectionStrings__Root=Server=postgres;User ID=postgres;Password=postgres;Port=5432;
      - Directory=./.migration
    networks:
      - my-network
    depends_on:
      - postgres
    links:
      - postgres
networks:
  my-network:
